# Generated by Django 4.0.4 on 2022-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoremanagement', '0002_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
