# Generated by Django 4.0.4 on 2022-04-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstoremanagement', '0003_delete_book_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_title', models.CharField(max_length=100)),
                ('store_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Post/imgs')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('book_stock', models.IntegerField(null=True)),
                ('comid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookid', to='bookstoremanagement.store')),
            ],
        ),
    ]
