# Generated by Django 4.0.4 on 2022-04-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoremanagement', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='comid',
            new_name='book_id',
        ),
    ]
