# Generated by Django 4.0.4 on 2022-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoremanagement', '0005_rename_comid_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='book_in_store',
        ),
    ]
