# Generated by Django 4.0.4 on 2022-04-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoremanagement', '0006_rename_book_id_book_book_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_edition',
            field=models.IntegerField(null=True),
        ),
    ]
